name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write

jobs:
  lint-python:
    name: Lint Python
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check changed py files
        id: changed-files
        uses: tj-actions/changed-files@v24
        with:
          files: |
            **/*.py

      - name: Set up Python
        uses: actions/setup-python@v1
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        with:
          python-version: 3.9

      - name: Install Python dependencies
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        run: pip install flake8

      - name: Run flake8 linter
        if: ${{ steps.changed-files.outputs.all_changed_files }}
        uses: wearerequired/lint-action@v2
        with:
          flake8: true
          flake8_auto_fix: false
          flake8_args: ${{ steps.changed-files.outputs.all_changed_files }}
          continue_on_error: false

  tests:
      name: tests
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code Repository
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.9'
            cache: pip

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install .

        - name: Run tests
          run: python manage.py test
